version: "3.9"

services:
  app:
    build: .
    container_name: device-data-hub
    restart: always
    volumes:
      - ddh-volume:/app/infra/database
    ports:
      - "5000:5000"

volumes:
  ddh-volume:
